package com.homejim.mybatis.mapper;

import com.homejim.mybatis.entity.Blog;
import com.homejim.mybatis.entity.BlogBO;
import com.homejim.mybatis.entity.BlogCustom;
import com.homejim.mybatis.entity.BlogPostBO;

import java.util.List;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    Blog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Blog record);

    /**
     * 根据博客的 id 获取博客及作者的信息
     * @param id
     * @return
     */
    BlogBO selectBoById(int id);
    /**
     * 根据博客的 id 获取博客及作者的信息
     * @param id
     * @return
     */
    BlogCustom selectCutomById(int id);

    /**
     * 根据博客的 id 获取博客及作者的信息, resultMap 方式
     * @param id
     * @return
     */
    BlogCustom selectCutomByIdMap(int id);

    /**
     * 根据博客的 id 获取博客及作者的信息, resultMap + association方式
     * @param id
     * @return
     */
    BlogCustom selectCutomByIdAMap(int id);

    /**
     * 根据博客的 id 获取博客及作者的信息, resultMap + association嵌套方式
     * @param id
     * @return
     */
    BlogCustom selectBlogAndAuthorByIdSelect(int id);

    /**
     * 获取博客及其发布的文章内容 一对多
     * @return
     */
    List<BlogPostBO> selectBlogAndPostList();

    /**
     * 获取博客及其发布的文章内容 一对多:延迟加载
     * @return
     */
    List<BlogPostBO> selectBlogAndPostListLazy();
}